### ISSUE TITLE
Can't download an episode, this week.

### ISSUE THREAD

**Issue by sirber** [bvanheu/pytoutv#131]
$ toutv fetch -q MAX "unite-9" s07e16
Unknown exception: <class 'RuntimeError'>: Exception has been thrown by the target of an invocation.

I reinstalled the package: pip3 install pytoutv
whitout solving the issue

**Comment by sirber** [comment]
other function works:

toutv list "unite-9"
Unité 9:

  * S01E01 - Épisode 01 - 19 mars 2013
  * S01E02 - Épisode 02 - 19 mars 2013
  * S01E03 - Épisode 03 - 19 mars 2013
...
  * S07E15 - Épisode 15 - 22 janvier 2019
  * S07E16 - Épisode 16 - 29 janvier 2019
  * S07E17 - Épisode 17 - 5 février 2019

**Comment by simark** [comment]
Confirmed:

```
DEBUG:ShelveCache:Trying to open shelve at /home/emaisin/.cache/toutv/.toutv_cache
_parse_show_episode_from_args returns: emission unite-9 and episode s07e16
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): ici.tou.tv
DEBUG:urllib3.connectionpool:https://ici.tou.tv:443 "GET /presentation//unite-9?v=2&d=android&excludeLineups=False HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): api.radio-canada.ca
DEBUG:urllib3.connectionpool:http://api.radio-canada.ca:80 "GET /validationMedia/v1/Validation.html?deviceType=iphone4&connectionType=wifi&idMedia=145094&appCode=toutv&output=json HTTP/1.1" 200 127
Unknown exception: <class 'RuntimeError'>: Exception has been thrown by the target of an invocation.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/toutvcli/app.py", line 110, in run
    args.func(args)
  File "/usr/local/lib/python3.5/dist-packages/toutvcli/app.py", line 506, in _command_fetch
    self._fetch_episode(episode, output_dir=output_dir, quality=quality, bitrate=bitrate, overwrite=overwrite)
  File "/usr/local/lib/python3.5/dist-packages/toutvcli/app.py", line 733, in _fetch_episode
    qualities = episode.get_available_qualities()
  File "/usr/local/lib/python3.5/dist-packages/toutv/bos.py", line 554, in get_available_qualities
    playlist, cookies = self.get_playlist_cookies()
  File "/usr/local/lib/python3.5/dist-packages/toutv/bos.py", line 542, in get_playlist_cookies
    url = self._get_playlist_url()
  File "/usr/local/lib/python3.5/dist-packages/toutv/bos.py", line 532, in _get_playlist_url
    raise RuntimeError(response_obj['message'])
RuntimeError: Exception has been thrown by the target of an invocation.
```

**Comment by JPLemelin** [comment]
Same here

```
(.venv36-64) λ toutv fetch 2424967431 S03E72 -q MAX
Unknown exception: <class 'RuntimeError'>: Exception has been thrown by the target of an invocation.
```

**Comment by philchamp** [comment]
Same here
`toutv fetch District\ 31 S03E77                                                                                                                                  Unknown exception: <class 'RuntimeError'>: Exception has been thrown by the target of an invocation.`

**Comment by martinayotte** [comment]
I've faced the issue in the recent days, but today it is working. So, probably Radio-Canada have been updated with a fix on server's side.

**Comment by sirber** [comment]
fixed for me!
