### ISSUE TITLE
UnicodeEncodeError when trying to download on Ubuntu 14.04

### ISSUE THREAD

**Issue by simark** [bvanheu/pytoutv#73]
I just tried to download an episode in an Ubuntu 14.04 container:

```
(env) root@06dca589bdcd:/pytoutv# toutv fetch Infoman S17E10
Unknown exception: <class 'UnicodeEncodeError'>: 'ascii' codec can't encode character '\xc9' in position 24: ordinal not in range(128)
Traceback (most recent call last):
  File "/pytoutv/toutvcli/app.py", line 94, in run
    args.func(args)
  File "/pytoutv/toutvcli/app.py", line 322, in _command_fetch
    bitrate=bitrate, overwrite=args.force)
  File "/pytoutv/toutvcli/app.py", line 594, in _fetch_episode_name
    bitrate=bitrate, overwrite=overwrite)
  File "/pytoutv/toutvcli/app.py", line 573, in _fetch_episode
    self._dl.download()
  File "/pytoutv/toutv/dl.py", line 290, in download
    self._init_download()
  File "/pytoutv/toutv/dl.py", line 142, in _init_download
    if not self._overwrite and os.path.exists(self._output_path):
  File "/env/lib/python3.4/genericpath.py", line 19, in exists
    os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode character '\xc9' in position 24: ordinal not in range(128)

```

**Comment by simark** [comment]
After investigating, it's an issue with the fact that I was in a container.  Docker doesn't set a UTF-8 locale, it defaults to:

```
LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
```

Setting `export LANG=C.UTF-8` makes it work.
