### ISSUE TITLE
"toutv --verbose" throws an exception

### ISSUE THREAD

**Issue by simark** [bvanheu/pytoutv#75]
```
$ toutv -v
Traceback (most recent call last):
  File "/home/simark/src/pytoutv-env/bin/toutv", line 9, in <module>
    load_entry_point('pytoutv==2.3.1', 'console_scripts', 'toutv')()
  File "/home/simark/src/pytoutv/toutvcli/app.py", line 667, in run
    return app.run()
  File "/home/simark/src/pytoutv/toutvcli/app.py", line 90, in run
    if args.build_client:
AttributeError: 'Namespace' object has no attribute 'build_client'
```

**Comment by simark** [comment]
Fixed as of today.
